# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15455ec3f24e42e207fcac608eaee280e3079b7abf6cfb0168bd059b2ef83e5f967f0bc18383cfa3a5df5b40b4ab1b7385dc835b445f98ab8224a25a1a66935d

test:
  secret_key_base: c6aec5820e37a762c8352738ef2a0fbeeea8c46a2e34b381aa8b9025dc9ee609f6d981b1b26b3d5dc9fda48a24e8a6158070a5107e2466fa8a728ed94c8536c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
